name: dartpedia001
description: Projeto Dartpedia para as aulas no SENAI.
version: 1.0.0

environment:
  sdk: '^3.0.0'

dependencies:
  http: ^1.2.0
  command_runner:
    path: ./command_runner
  logging: ^1.3.0
dev_dependencies:
  test: ^1.32.0
